name = "fist"
version = "1.7.0"
description = "a pure, declarative router for Gleam"
licences = ["Apache-2.0"]

[repository]
type = "codeberg"
user = "MrTomate"
repo = "fist"

links = [
  { title = "Repository", href = "https://codeberg.org/MrTomate/fist" },
  { title = "Hex Package", href = "https://hex.pm/packages/fist" },
]

internal_modules = ["fist/internal", "fist/internal/*"]

[javascript]
typescript_declarations = true

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
mist = ">= 6.0.0 and < 7.0.0"

[[documentation.pages]]
title = "User Guide"
path = "guide.html"
source = "docs/guide.md"

[[documentation.pages]]
title = "Core Concepts"
path = "behavior.html"
source = "docs/behavior.md"

[[documentation.pages]]
title = "Advanced Patterns"
path = "advanced.html"
source = "docs/advanced.md"

[[documentation.pages]]
title = "Roadmap"
path = "roadmap.html"
source = "docs/roadmap.md"
