name: Deploy docs to GitHub Pages

on:
  push:
    branches: ["master", "main"]

# Necessary permissions to publish to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: uses/checkout@v4

      - name: Setup Erlang and Gleam
        uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1.14.0"
          rebar3-version: "3"

      - name: Download deps
        run: gleam deps download

      - name: Build docs
        run: gleam docs build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # The exact path where Gleam generates documentation for the 'fist' package
          path: "./build/dev/docs/fist/"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
